### ISSUE TITLE
RL Calamares branding is not removed

### ISSUE THREAD

**Issue by cat-master21** [rhino-linux/os#41]
In RL 2023.1 the branding for RL is still at /etc/calamares/branding and should be removed after installation. https://github.com/rhino-linux/os/blob/c46c3b16f3e7596b5049c61b154dc6e47d0cfe90/etc/config/hooks/live/099-install-custom-apps.chroot#L151C27-L151C27

**Comment by ajstrongdev** [comment]
@cat-master21 Are you able to handle this?

**Comment by cat-master21** [comment]
Yeah @ajstrongdev I can do this
