### ISSUE TITLE
BUG: Full Disk Encryption Not Working

### ISSUE THREAD

**Issue by seangould** [rhino-linux/os#47]
**Rhino Linux Version:**
2023.1

**Platform:**
x86_64

**Describe the bug**
When installing rhino linux with full disk encryption, mounting the encrypted volume fails during boot process.

**To Reproduce**
1. Select encryption during the installation process
2. Reboot
3. Enter the password for the encrypted disk when prompted
4. You'll get an error after a bit of a hang during the boot process, and are unable to boot into the system 

**Expected behavior**
The encrypted volume to be decrypted and boot into rhino linux

**Screenshots**
![rhino-encryption-error](https://github.com/rhino-linux/os/assets/2576039/822f4ec5-79f5-493c-a2c9-211a7ecee984)

**Additional context**
This occurred for me both when installing into a vm for testing, as well as on physical hardware (amd laptop)

**Comment by oklopfer** [comment]
Already solved, see https://github.com/rhino-linux/os/pull/46
