### ISSUE TITLE
Add: Timeshift

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#50]
Add a method similar to `arch-chroot` to recover an unbootable system.

**Comment by oklopfer** [comment]
Do you just mean chroot? because, if you have an extra Debian/Ubuntu USB stick, then this solution already exists.

**Comment by ajstrongdev** [comment]
Yeah but make the process simpler for users.

**Comment by TActually** [comment]
I think a faster method for less advanced users for recovery would be the inclusion of a backup utility like Timeshift.
Timeshift is written around rsync but also supports btrfs, so it will work for just about any installation method that people choose.

As an added bonus, rhino could be an iso included in people's rescue toolkits, which is good for branding.

**Comment by tripleo1** [comment]
https://github.com/digint/btrbk

**Comment by ajstrongdev** [comment]
> https://github.com/digint/btrbk

Rhino Linux by default does not utilise btrfs, and so Timeshift still seems like the best option.

**Comment by tripleo1** [comment]
On 9/4/23 1:12 PM, AJStrong ***@***.***> wrote:
>     https://github.com/digint/btrbk <https://github.com/digint/btrbk>
> 
> Rhino Linux by default does not utilise btrfs, and so Timeshift still 
> seems like the best option.
> 

FWIW, my Rhino is on btrfs.

May I inquire as to why btrfs is not your preferred option?

**Comment by ajstrongdev** [comment]
> On 9/4/23 1:12 PM, AJStrong ***@***.***> wrote:
> >     https://github.com/digint/btrbk <https://github.com/digint/btrbk>
> > 
> > Rhino Linux by default does not utilise btrfs, and so Timeshift still 
> > seems like the best option.
> > 
> 
> FWIW, my Rhino is on btrfs.
> 
> May I inquire as to why btrfs is not your preferred option?
> 

There was no specific decision not to utilise btrfs by default. Ubuntu currently still utilises ext4, and since this distribution is essentially Ubuntu as a rolling release, no specific changes were made to the default file system. Users are still able to manually create a btrfs file system if they choose so, however, and I would not be opposed to implementing btrfs in the future, however that's a discussion that needs to be had between the systems team, as I handle desktop UI/UX development.
