### ISSUE TITLE
Proposal: Development library opt-in pacstall repository

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#51]
An idea for a pacstall repository ran by the Rhino Linux team that houses development libraries such as `rust`, `valac` `libadwaita-dev` etc.

**Comment by oklopfer** [comment]
DEFINITELY not. too much to maintain. Pacstall is our repo.

**Comment by ajstrongdev** [comment]
As a distribution geared towards developers I think it's a perfectly good idea. We can always find more pacscript maintainers.

**Comment by ajstrongdev** [comment]
Closed. Not happening.
