### ISSUE TITLE
BUG: Bluetooth support on some devices

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#52]
**Rhino Linux Version:**
2023.1 & 2023.2

**Platform:**
AMD64, likely extends to ARM devices.

**Describe the bug**
Bluetooth doesn't work properly on some devices. Cannot connect or find the device.

**Expected behavior**
Bluetooth can be found and works properly

**Additional context**
No known proprietary driver issues, as some users experience this on Intel AX201.

**Comment by cat-master21** [comment]
Yeah I have a AX200 (maybe AX201) I can test at some point.

**Comment by cat-master21** [comment]
So @ajstrongdev the bluetooth worked perfectly for me: AX200 and ASUS USB-BT500 on the same machine.

**Comment by oklopfer** [comment]
@cat-master21 it is specifically in regards to Bluetooth keyboards and mice not being detected. Bluetooth audio devices are being detected but have poor quality.

**Comment by nbattista89** [comment]
Hi,
I can confirm that with AX201 i've the same issue (doesn't view the mouse)

**Comment by TActually** [comment]
So my experience with this is a bit different from everyone elses.
I have Dell latitude E7470:
i7, 6th gen, hd620 graphics
32gig DDR4 ram
512gb SSD
Intel ibt-11-5 bluetooth device

I was able to successfull connect to and use a bluetooth keyboard: RK84.
I was able to connect to and succesfully use a bluetooth headset: Jabra Evolve65
But, I was not able to use my Bose bluetooth headphones nor a pair of "amazon specials".
The headphones would connect, but they would not show up in pavucontrol.

**Comment by ajstrongdev** [comment]
So this is quite a unique issue. My main concern is that it only seems to affect intel AX200 and 201. Kernel support for AX201 was added in kernel 5.15, which was in 2021. 

Issues with AX201 wireless and bluetooth have been documented recently here: https://community.intel.com/t5/Wireless/Intel-AX201-ubuntu-firmware-issue/td-p/1509398 however it seems to be a different bug.

Will require more investigation but this is what I've found so far while looking into it

**Comment by ajstrongdev** [comment]
Some further digging seems to show a similar issue with Arch Linux on the 6.4 zen kernel. It is important to note that the Zen kernel is not an official kernel, and this is a different distribution, but apparently according to another comment using an LTS kernel does work. If someone experiencing this issue can test their wireless setup with AX201 and an LTS linux kernel, and comment on if it works, that would be useful.

https://community.intel.com/t5/Wireless/Intel-AX201-Bluetooth-Issues-connecting-to-logitech-products-on/td-p/1516183

**Comment by ajstrongdev** [comment]
@oklopfer Have any changes been made to make this under review?

**Comment by oklopfer** [comment]
@ajstrongdev yeah I updated some deps for unicorn, waiting for confirmations from people now

**Comment by ajstrongdev** [comment]
@oklopfer Have you received any confirmations or have any new issues cropped up?

**Comment by oklopfer** [comment]
I've received more confirmations yeah. I think we can say this is closed finally.
