### ISSUE TITLE
BUG: connecting to wifi on embedded

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#54]
**Rhino Linux Version:**
2023.2

**Platform:**
Embedded devices - Pine64 & Raspberry Pi

**Describe the bug**
Need to add gnome-keyring to embedded devices by default because the Wireless connect prompt does not give a pop-up.

**Comment by ajstrongdev** [comment]
@oklopfer Any update?

**Comment by oklopfer** [comment]
tested and still not fixed. have to rollover

**Comment by oklopfer** [comment]
fixed (magically)
