### ISSUE TITLE
BUG: Raspberry Pi "Your System" application does not follow libadwaita theming

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#55]
**Rhino Linux Version:**
2023.2

**Platform:**
Raspberry Pi (Desktop)

**Describe the bug**
Once the distribution is installed, The "Your System" application does not follow libadwaita theming.

**Comment by oklopfer** [comment]
issue confirmed, no idea how to solve.... super weird yaru bug that hope will just be fixed later....

**Comment by ajstrongdev** [comment]
@oklopfer Since this seems to be a bug with Yaru shall I move to Rollover?

**Comment by ajstrongdev** [comment]
Moved to rollover.

**Comment by ajstrongdev** [comment]
@oklopfer Has noted that since updating it has been solved on his machine, however on mine (ARM64) after updating no changes.

**Comment by oklopfer** [comment]
Bruh seriously

**Comment by oklopfer** [comment]
Still have no idea what’s causing this. It’s especially weird that the colors change, but not light/dark difference.

**Comment by oklopfer** [comment]
I.... fixed it. https://github.com/rhino-linux/rhino-system/commit/9dbc6c8ba47a05d11237ed9221debcb6e42e90cc
