### ISSUE TITLE
 BUG: Installer will not boot after grub select for Intel Nuc 12 Extreme (Serpent Canyon). Stuck on "EFI stub: Measured initrd data into PCR 9"

### ISSUE THREAD

**Issue by Daxiongmao87** [rhino-linux/os#58]
Rhino Linux Version:
2023.3

Platform:
amd64

Describe the bug
I used Ventoy to create a bootable usb. I have disabled secure boot. I select Rhino Linux within Ventoy boot screen. It then directs me to the grub boot screen. I've tried both normal and safemode options for 'try/install Rhino Linux,' as well as OEM install option. However, the same result occurs -- a blank screen.

Using the boot parameter nomodeset, I am greeted with EFI stub: Measured initrd data into PCR 9, to which the boot stays, and does not progress further.

To Reproduce

    Write ISO to USB using Ventoy
    Disable Secure Boot
    Boot into Rhino Linux installer and select grub options, enter nomodeset (to see text output)
    Stuck on 'Select boot option for usb disk (using vent'

Expected behavior

    Write ISO to USB using Ventoy
    Disable Secure Boot
    Boot into Rhino Linux installer and select grub options, enter nomodeset (to see text output)
    Boot into live version of Rhino Linux

Screenshots
N/A

Additional context
I have installed the latest BIOS version for my machine.
Here is a link to the NUC I am using: https://www.intel.com/content/www/us/en/products/sku/196170/intel-nuc-12-enthusiast-kit-nuc12snki72/specifications.html

**Comment by Elsie19** [comment]
Sorry for a late reply 😅 did you try without ventoy?

**Comment by Daxiongmao87** [comment]
Hey Elsie, sorry I just saw this, using something other than Ventoy worked.  Ventoy seems to cause trouble during boot.
