### ISSUE TITLE
ENH: Update PinePhone & PinePhone Pro kernels to 6.6rc5 from Megi

### ISSUE THREAD

**Issue by marek-lach** [rhino-linux/os#61]
**Rhino Linux Version:**
2023.3

**Platform:**
PinePhone Pro

**Expected behavior**
Please update the kernels for the [PinePhone](https://xff.cz/kernels/6.6/pp.tar.gz) and also the [PinePhone PRO](https://xff.cz/kernels/6.6/ppp.tar.gz) to version 6.6rc5.

**Comment by oklopfer** [comment]
https://github.com/pacstall/pacstall-programs/commit/b8fbaba0c5f905c57fb5c29dd6d0f51cf712c4c4 they already have been.

**Comment by marek-lach** [comment]
> [pacstall/pacstall-programs@b8fbaba](https://github.com/pacstall/pacstall-programs/commit/b8fbaba0c5f905c57fb5c29dd6d0f51cf712c4c4) they already have been.
> 
> Also, we use my own custom kernels, not Megi. We had it out over a week ago, and are due for rc7 on Sunday.

Oh, cool. Thanks.
