### ISSUE TITLE
Enh: find alternative for kernel releasing

### ISSUE THREAD

**Issue by oklopfer** [rhino-linux/os#63]
Ubuntu’s mainline repo has been down for over a month now. We need a solution for building our kernels readily on time, both for mainline regular and stable. 

Also, I need to get 6.7-rc1+ working for pine, it has merge conflicts right now

**Comment by ajstrongdev** [comment]
As someone with more insight and knowledge, how would you consider we handle this?

**Comment by cat-master21** [comment]
Well, maybe it would be best to rely on a 3rd-party like https://github.com/zabbly/linux for the time being but if it is too uncertain/unsecure then perhaps not.

**Comment by ajstrongdev** [comment]
Ubuntu mainline kernels have began building again, while it would be nice to find a more stable alternative for kernel releasing, this is no longer considered critical. Moving to rollover for a long-term fix.

**Comment by oklopfer** [comment]
Not worth keeping as an issue now that it’s fixed for Ubuntu. We have it in the back of our minds.
