### ISSUE TITLE
BUG: `rhino-setup` is not reliably installed by calamares

### ISSUE THREAD

**Issue by oklopfer** [rhino-linux/os#64]
every 10th user or so reports rhino-setup not being launched in post-installation, which is due to calamares not installing it correctly. This should be fixed hopefully for 2023.4. The current method is already quite hacky-cheatsy, so we can find a different hacky-cheatsy way to do it. Before, it was auto-installed by default, and then was to put an autostart file in the user's config for it. but maybe I can instead have it auto-installed by default, have it place an /etc/skel file, and then make sure the rhino-live user does not receive the file. this is probably what I should do.

**Comment by oklopfer** [comment]
https://github.com/rhino-linux/os/commit/ea37686fabd24a472795cb2a0ac53f1993d7f009
https://github.com/pacstall/pacstall-programs/commit/002b11ab370976eba5a9660da901386a02e5ab99
need to see if it works

**Comment by Elsie19** [comment]
Have we determined the reason why it sometimes works and sometimes doesn't?

**Comment by oklopfer** [comment]
Calamares was set to install it, but sometimes failed on the step and just kept going. I’ve just turned it back to pre installed.

**Comment by oklopfer** [comment]
confirmed it is now pre-installed on live images but doesn't autostart for rhino-live user; can now close
