### ISSUE TITLE
enh: Upgrade kernel to 6.6.6

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#66]
Kernel 6.6.6 builds have succeeded, we should upgrade the kernel before 2023.4 release.

**Comment by oklopfer** [comment]
https://kernel.ubuntu.com/mainline/v6.7-rc5/
https://kernel.ubuntu.com/mainline/v6.6.6/

**Comment by oklopfer** [comment]
https://github.com/pacstall/pacstall-programs/commit/3188bdc0e7e0ef40dde7e8289f126e1267fef793
