### ISSUE TITLE
Feat: Shorten build process with livebuild

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#67]
Apparently there is a method on how to speed up the build process with livebuild.

Potential answer: https://lists.debian.org/debian-live/2017/02/msg00010.html

**Comment by oklopfer** [comment]
@ajstrongdev that answer is not related. the specific issue is that live-build is single-core processing, when we want it to parallel process

**Comment by DakJack** [comment]
I have been using eatmydata and it appears to be processing slower.
Could be my specific setup, but that may be worth reviewing.

**Comment by DakJack** [comment]
I'm not sure if you're able to select the server architecture in GitHub actions, but the builds for the PinePhone are much much faster on my RK3588 Orange Pi 5 Plus than my Ryzen 7 5800U laptop.

**Comment by oklopfer** [comment]
Oh yeah, we have utilized native arm64 runners since the beginning.
