### ISSUE TITLE
BUG: Parallels Tools Installation Failure on Rhino Linux with Kernel 6.6.7

### ISSUE THREAD

**Issue by ylluminate** [rhino-linux/os#68]
**Rhino Linux Version:**
Rhino Linux 2023.4 (mainline) - devel

**Platform:**
arm64 via MacBookPro18,2 (M1 Max) with macOS 14 via Parallels 19.2.0 (54827)

**Describe the bug**
Parallels Tools installation fails on Linux kernel version 6.6.7-060607-generic. The process halts during the compilation of kernel modules, particularly encountering issues with `fixdep` (which can be manually compiled) and then `genksyms` (which then seems to fail with all attempts to manually compile), part of the kernel headers.

**To Reproduce**
1. Attempt installation of Parallels Tools using the provided script (used the shell-based version via `sudo ./media/u/Parallels\ Tools/install -i --verbose`.
2. Install `build-essential`, `linux-headers-$(uname -r)`, and `gcc-13`.
3. Encounter error: `modprobe: FATAL: Module prl_tg not found`.
4. Manually compile kernel modules from `/usr/lib/parallels-tools/kmods`.
5. Rebuild `fixdep` successfully, but face linking errors with `genksyms` due to undefined references to `yydebug`.

**Expected behavior**
Successful compilation of `genksyms` and completion of the Parallels Tools installation process.

**Additional context**
- GCC Version: 13.2.0
- Architecture: arm64
- Efforts to resolve included reinstalling `binutils`, `gcc`, `make`, and relevant linux headers.
- Defined and exported `CC` environment variable to `/usr/bin/gcc-13`.
- Manual compilation steps involved `bison` and `flex` processing, object file generation, and final linking with `-lfl` and `-ly` flags.
- Persistent issue with `genksyms` linking errors as follows:
    ```
    /usr/bin/ld: genksyms.o: in function 'main':
    genksyms.c:(.text+0x2278): undefined reference to 'yydebug'
    collect2: error: ld returned 1 exit status
    ```

During the initial install attempt the following came from the `parallels-tools-install.log`:
```
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[4]: *** [scripts/Makefile.build:243: /usr/lib/parallels-tools/kmods/prl_tg/Toolgate/Guest/Linux/prl_tg/prltg.o] Error 126
make[4]: *** Deleting file '/usr/lib/parallels-tools/kmods/prl_tg/Toolgate/Guest/Linux/prl_tg/prltg.o'
```
After manually compiling that, I got the following:
```
/bin/sh: 1: scripts/genksyms/genksyms: Exec format error
make[4]: *** [scripts/Makefile.build:243: /home/u/tmp/prl_mod/prl_tg/Toolgate/Guest/Linux/prl_tg/prltg.o] Error 126
make[4]: *** Deleting file '/home/u/tmp/prl_mod/prl_tg/Toolgate/Guest/Linux/prl_tg/prltg.o'
```
When I tried to compile genksyms manually I experienced the error shared above pertaining to genksyms.

**Comment by oklopfer** [comment]
BTW this probably looks like a PRL tools issue, and not an us issue (I can't find any mention of them supporting 6.6 series at all)
