### ISSUE TITLE
Feat: Ditch calamares in favour of a new installer.

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/os#69]
A proposal brought about by both @oklopfer and @ajstrongdev for ditching Calamares in favour of a new installer for 2024.1.

**Why ditch calamares:**
- The installer looks rather ugly
- In that same essence, we pull in qt weight for Kvantum + Calamares, it would be nicer to drop it in favour of a pure GTK4 application.
   - This would make our disk image builds smaller as well.

**Comment by ajstrongdev** [comment]
We could use https://gitlab.gnome.org/p3732/os-installer as a solid base to work from if we are creating a GTK4 based installer.

If we wish to have a more macOS-like installer, we could always look at forking: https://github.com/elementary/installer

**Comment by Elsie19** [comment]
I disagree, calamares is well established, and it being "ugly" is entirely our fault:

![image](https://github.com/rhino-linux/os/assets/58742515/a1c68b68-02e5-48d0-8186-88716fd8ec83)

https://nxos.org/news/updates-calamares-qml/

to give a couple examples.

**Comment by ajstrongdev** [comment]
> I disagree, calamares is well established, and it being "ugly" is entirely our fault:

I completely agree with that to be honest. But I do not disagree with the first points raised. We use a GTK based environment, we should aim to keep our installer GTK-based as well.

Nitrux clearly customised calamares correctly though.

**Comment by Elsie19** [comment]
You also mention bloat, but have you actually measured the installable difference?

**Comment by Elsie19** [comment]
We've determined the bloat is about 16MB *uncompressed*, so it would be further compressed when the ISO is packed.

**Comment by ajstrongdev** [comment]
> We've determined the bloat is about 16MB _uncompressed_, so it would be further compressed when the ISO is packed.
It's pretty evident your math is wrong on that. Are you literally only checking Kvantum instead of Calamares + all the QT dependencies?

**Comment by Elsie19** [comment]
That's only kvantum, I am checking Calamares right now.

**Comment by Elsie19** [comment]
200MB.

**Comment by oklopfer** [comment]
elsie been lying on us this whole time
its approx 360MB on the ISOs, not including kvantum
regardless, I dont want Qt defaults in our GTK enviro.

**Comment by maki406** [comment]
🐱

**Comment by holysses** [comment]
I agree with Elsie calamares is long established it works just change the themeing if you do not like it

**Comment by Elsie19** [comment]
> elsie been lying on us this whole time its approx 360MB on the ISOs, not including kvantum regardless, I dont want Qt defaults in our GTK enviro.

I checked in a docker container with XFCE already installed to get a good idea of what adding `calamares` would cost, so I didn't *lie*, it was just not the right number that the ISO actually uses.

**Comment by ajstrongdev** [comment]
The community seems pretty clear in their wants and needs; developing an entirely new installer is a large undertaking and would divert a lot of resources when we could just make calamares more pretty. 

The main concern is we can decrease the disk image size and not have any QT spill over in a GTK based environment.

**Comment by Elsie19** [comment]
As I've said in channels but I'll put it here as well, we can use `apt install --no-install-recommends` in certain places where we call apt to remove some of that image dize.

As for not having any QT spill over, we can remove kvantum along with calamares when the system installs.

**Comment by oklopfer** [comment]
We can’t use that flag because it’s just a package list for live-build, it’s not a custom install step. So no, we can’t easily get rid of the bloat without getting rid of Calamares altogether. 

Also, we already do remove the dependencies post-install. But that means they still bloat up the ISO, which could be shrunk down quite a bit.

**Comment by ajstrongdev** [comment]
> We can’t use that flag because it’s just a package list for live-build, it’s not a custom install step. So no, we can’t easily get rid of the bloat without getting rid of Calamares altogether.

This is a very good point, as someone who is on the fence at the moment both ideas have merit to me.
