### ISSUE TITLE
bug: grub says ubuntu and not rhino

### ISSUE THREAD

**Issue by oklopfer** [rhino-linux/os#71]

**Comment by oklopfer** [comment]
/etc/default/grub GRUB_DISTRIBUTOR needs to be changed to Rhino

**Comment by ajstrongdev** [comment]
Update @oklopfer?

**Comment by oklopfer** [comment]
nothing yet, I think this is partially related to calamares

**Comment by lbtbs** [comment]
> /etc/default/grub GRUB_DISTRIBUTOR needs to be changed to Rhino

How to do it exactly? Which commands do I need to use?

**Comment by nathantlong** [comment]
___IF___ this is pulling from branding.desc in the calamares stuff then I think I just fixed it.

**Comment by oklopfer** [comment]
> _**IF**_ this is pulling from branding.desc in the calamares stuff then I think I just fixed it.

Care to share more?

**Comment by nathantlong** [comment]
Sorry--super noob here.  

In branding.desc, `bootloaderEntryName: Rhino` > `bootloaderEntryName: Rhino`

**Comment by nathantlong** [comment]
> Sorry--super noob here.
> 
> In branding.desc, `bootloaderEntryName: Ubuntu` > `bootloaderEntryName: Rhino`

Also, I'm running Rhino on a Pi 5, so I don't have a grub-enabled machine to test it on...I'll try to run a Docker container on my laptop at some point soon to confirm if it made a difference...assuming I can figure out getting the bootloader to show up in a container...

Like I said, noob, lol.

**Comment by oklopfer** [comment]
You’ve provided plenty 😁 you’ll have a hard time testing the change in docker. But I will test it myself this weekend on some images and report back!

**Comment by nathantlong** [comment]
Happy to help (assuming it helps)!  Also, snazzy distro--really digging where it's heading & excited to be along for the ride...y'know,  occasionally pointing out things I see from the back seat. 😁

**Comment by oklopfer** [comment]
https://github.com/rhino-linux/calamares/commit/6f4a56369b6edc40cfac1cfe982faf02ce77047d
