### ISSUE TITLE
Live boot login password needed

### ISSUE THREAD

**Issue by Kaif21** [rhino-linux/os#78]
Hello. So i made an custom rhino Linux iso for my students using Cubic(Custom Ubuntu ISO Creator). When I opend the custom ISO in the VMware workstation 17 player it's asking me to provide password. But I just booted to live cd. So what will be my password for Live boot? 

![10a1f1df-a17b-468f-90ad-aba6c51fc096.jpg](https://github.com/rhino-linux/os/assets/62374060/2f08df74-7b70-458d-8416-d66af39a8f60)

**Comment by PoggerLogger** [comment]
Other ISO builders aren't supported.
