### ISSUE TITLE
BUG: mobile-usb-networking removal fails in chroot

### ISSUE THREAD

**Issue by tromshusky** [rhino-linux/os#80]
**Rhino Linux Version:**
2024.1

**Platform:**
aarch64 / pinetab2 

**Describe the bug**
mobile-networking-usb cant be removed from chroot

**To Reproduce**
1.  Download latest pinetab2 image 
2.  Mount image ( loopdevice (`losetup /dev/loop0 img.img`, `partprobe /dev/loop0`, `mkdir mnt && mount /dev/loop0p2 mnt`) 
(3. ```# cd mnt && mount -t proc proc proc && mount --rbind /sys sys && mount --rbind /dev dev && chroot . ```)
4. ```apt remove rhino-pine-core -y --allow-remove-essential ```
5. ```apt remove mobile-usb-networking -y ```
 apt remove returns error code 1

**Expected behavior**
package uninstallation finishes without error

**Screenshots**
![Screenshot from 2024-06-09 07-43-43](https://github.com/rhino-linux/os/assets/170419266/8e0dcfb2-557c-4a1b-8512-b84eea299d6e)

**Additional context**
the preremoval script in `/var/lib/dpkg/info/mobile-usb-networking.prerm` doesnt work in chroot, like other packages do.
commenting this script results in successful removal.

Additionally, this package caused me boot hanging for 2 minutes in a stripped down os, and keeps on adding USB networking devices again and again.

**Comment by oklopfer** [comment]
You’re removing critical packages that allow rhino linux to function properly and remain updated to our releases. Please don’t remove a core. If you really want to strip down your image, you install `rhino-server-core` which will auto replace another core, but `mobile-usb-networking` is so you can connect to your pinetab2 over ssh through a cable connection. It is a small file and removing it is removing capabilities from your device.
