### ISSUE TITLE
BUG: [not quite sure] uhm i got tracebacks and dunno whadda do (-:

### ISSUE THREAD

**Issue by mcwimpy** [rhino-linux/os#81]
**Rhino Linux Version:**
2024.1

**Platform:**
[~] ritux@hpprobook6560b $ inxi
CPU: dual core Intel Core i3-2310M (-MT MCP-) speed/min/max: 798/800/2100 MHz
Kernel: 6.5.6-060506-generic x86_64 Up: 1h 18m Mem: 2.97/7.67 GiB (38.8%)
Storage: 134.17 GiB (23.7% used) Procs: 229 Shell: Bash inxi: 3.3.34

**Describe the bug**
well the firefox browser wouldn't update to v127 which is out for days now... so i tried installing alternatives like nightly and some such. that lead to weird output i've never seen before. (gotta say though yourses and garuda command line stuff look the coolest of all distro's. especially the errors :-)

**To Reproduce**
1. do system update
2. try install with rhino-pkg
3. try install with apt
4. try install with pacstall
5. use official mozialla method: https://support.mozilla.org/en-US/kb/install-firefox-linux
6. look stupid
7. stare holes into the air
8. reinstall operating system
9. make faces
10. try look intelligent for a change
11. try stare holes into the laptop

**Expected behavior**
uhm,,,, points 6+ shoulda really have saved me... but then again, i guess i'm not all that good in linuxing (-;
 ok for real now:

 1st:
===
 the desktop switcher should ALLWAYS go away when i select a window. (sometimes it don't go away no matter what you do, takes minutes of random clicking to get rid of that.)

2ndly: i had hoped grub-customizer works well (see ss01) please take a look
=====
3rdly: firefox should always be latest version
=====
last but not least:
==============
dunno what ya'll wanna do with all those error messages but i feel you might have wanted me never to see them in the first place and hope this can all help you to improve your still young distro. cudos, it's really one of the coolest of all and even in design and ideas top notch and bleeding edge. good success and have fun peeps!

love from Vienna.

**Screenshots**
![ss01](https://github.com/rhino-linux/os/assets/11300847/51b273a6-fca9-4875-97f9-3b5378351c38)
![ss02](https://github.com/rhino-linux/os/assets/11300847/8d25e978-e024-419f-8bfa-59a644554d78)

**Additional context**
gotta say yourses and garuda command line stuff look the coolest. i would even say your distro is top 3. (i tested about 3 dozen top ones in distrowhatch) there's hardly any trash distros out there or teams that don`t appreciate users trying to help them by donating resources like time, money, nerves and efforts... { \BEWARE } the only REAL crap of the worst kind with the most evil people on the team is vanillaOS, some of them should work on a change of mindset, do some psych- therapy and mark their stable as pre-alpha (and keep that beta shait hidden from public...) { \BEWARE } however that all may be... i'm including logfiles and screenshots. { \BEWARE } 

[installation-error-log-240616a.text.txt](https://github.com/user-attachments/files/15857603/installation-error-log-240616a.text.txt)

[installation-error-log-240616b.text.txt](https://github.com/user-attachments/files/15857602/installation-error-log-240616b.text.txt)

**Comment by mcwimpy** [comment]
https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions

**Comment by ajstrongdev** [comment]
This is an issue with Pacstall. The Pacstall firefox package was not updated to the latest version immediately however it should be out now.
