### ISSUE TITLE
BUG: VSCodium can't store GitHub creds in keyring

### ISSUE THREAD

**Issue by Luiggi33** [rhino-linux/os#82]
**Rhino Linux Version:**
2024.1

**Platform:**
ASUSTeK COMPUTER INC. UX425QA

**Describe the bug**
When logging in with GitHub in VSCodium, I ran into the error "You're running in a GNOME environment but the OS keyring is not available for encryption. Ensure you have gnome-keyring or another libsecret compatible implementation installed and running.".  This meant I couldn't interact with private repositories.

**To Reproduce**
1. Open VSCodium in a private repository
2. Run git fetch
3. Login with GitHub and allow VSCode as an app

**Expected behavior**
The credentials get saved into the keyring without errors

**Additional context**
I could resolve the issue using the workaround in https://github.com/microsoft/vscode/issues/194530

**Comment by oklopfer** [comment]
https://github.com/rhino-linux/unicorn/commit/9e6fe0e00a14e5bee676579f8ff131e6a5b85a71 this should be solved with an update to unicorn now. let me know if your issue is fixed after updating.
