### ISSUE TITLE
BUG: visudo uses alien key bindings

### ISSUE THREAD

**Issue by iconoclasthero** [rhino-linux/os#84]
For some reason the keybindings in visudo are not the standard nano keybindings and I have no idea where the config for this is.  It isn't defined in the man file or /etc/sudo.conf and I have no idea why the Rhino version must necessarily be different from the Ubuntu one just to make life more difficult.

Where are these keybindings defined?

**Comment by Elsie19** [comment]
This is because of a recent nano update where the commands changed. I believe @oklopfer knows what the command to get them back are.

**Comment by oklopfer** [comment]
It is a stupid new configuration with nano: https://lwn.net/Articles/971980/

for some reason, `editor`/`sensible-editor` forces this new flag on. For me, setting the envar `EDITOR="nano"` in my profile fixes it for pacstall.
