### ISSUE TITLE
"Install Rhino" icon is not on the desktop or dock when booting the live USB

### ISSUE THREAD

**Issue by ObsidianRazor** [rhino-linux/os#85]
When booting the Live USB, the "Install Rhino" icon/shortcut is not visible either on the desktop or the dock.

You can find it by going into the app launcher, which is not the most horrible of bugs, but a new user might get confused.

**Comment by oklopfer** [comment]
https://github.com/rhino-linux/os/commit/8e07dbde7c8a8d975121a3a512f05150ef4f67a2

**Comment by oklopfer** [comment]
the icon appears to be back from the latest test, should be there in next ISO release
