### ISSUE TITLE
BUG: setup-casper-folder.binary hook partially fails

### ISSUE THREAD

**Issue by villamorrd** [rhino-linux/os#96]
**Rhino Linux Version:**
`2024.2`

**Platform:**
`amd64`

**Describe the bug**
When executing setup-casper-folder.binary, it fails to move initrd and vmlinuz files from the live folder to the casper folder.
```bash
P: Executing hook config/hooks/live/setup-casper-folder.binary...
mv: cannot stat 'live/filesystem.size': No such file or directory
mv: target 'casper/initrd.lz': No such file or directory
mv: target 'casper/vmlinuz': No such file or directory
```

**To Reproduce**
```bash
sudo apt-get update && sudo apt-get install --reinstall debootstrap -y
sudo mv /usr/share/debootstrap/functions functions
sudo patch -i 0002-remove-WRONGSUITE-error.patch
sudo mv functions /usr/share/debootstrap/functions
sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/noble
sudo dpkg -i debs/live-build_*_all.deb
sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi
sudo chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/
```

**Expected behavior**
The `casper` folder should have `initrd` and `vmlinuz` files in the final ISO image build.

**Screenshots**
![image](https://github.com/user-attachments/assets/a6b3b55b-02a5-4af2-8f53-7a0dc01f6edb)

**Comment by cat-master21** [comment]
@villamorrd Check to see if this issue still persists, as I do not have this issue on the latest commit just pushed [93c7c8b](https://github.com/rhino-linux/os/commit/93c7c8bc08ace0907fca65e019f1e4aa81f69e4f).

**Comment by villamorrd** [comment]
> @villamorrd Check to see if this issue still persists, as I do not have this issue on the latest commit just pushed [93c7c8b](https://github.com/rhino-linux/os/commit/93c7c8bc08ace0907fca65e019f1e4aa81f69e4f).

Seems to be resolved.
